In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer

In [3]:
df = pd.read_csv('/Users/anastasiiamorozova/Downloads/drugs-demo/demo - narko.csv')

In [6]:
# Convert labels from strings to sets
df["label_set"] = df["label"].str.replace("\[*\]*,*", "", regex=True).str.split().apply(set)

In [7]:

# Convert labels to a binary format for multi-label classification
# delivery, drugs, non-drugs, price
mlb = MultiLabelBinarizer()

# Extract features
X = df['message']
y = mlb.fit_transform(df["label_set"])

# Display classes
print(f"Classes: {mlb.classes_}\n---\n")

# Display labels
print("Binary Labels:\n", y)

Classes: ['cena' 'dostawa' 'narkotyki' 'nienarkotyki']
---

Binary Labels:
 [[1 0 1 0]
 [0 0 0 1]
 [0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 1 0]
 [0 1 0 1]
 [1 0 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 1]
 [0 0 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [1 0 0 1]
 [1 0 1 0]
 [0 0 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 0 1]
 [1 0 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 0 1]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 0 0 1]
 [0 0 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 0 1 0]


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.pipeline import Pipeline

In [9]:
# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Define the pipeline
pipeline = Pipeline([
    ('vectorizer', TfidfVectorizer(max_df=0.9, max_features=2500)),
    ('clf', MultiOutputClassifier(estimator=LogisticRegression(multi_class='auto')))
])

In [11]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Model Training with hyperparameter tuning
pipeline = Pipeline(steps = [
    ('vectorizer', TfidfVectorizer(max_df=0.9, max_features=2500)),
    ('clf', MultiOutputClassifier(estimator=LogisticRegression(multi_class='auto')))])

pipeline.fit(X_train, y_train)

/Users/anastasiiamorozova/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/anastasiiamorozova/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/anastasiiamorozova/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/anastasiiamorozova/.pyen

Pipeline(steps=[('vectorizer', TfidfVectorizer(max_df=0.9, max_features=2500)),
                ('clf',
                 MultiOutputClassifier(estimator=LogisticRegression(multi_class='auto')))])

In [12]:
text_messages = ["wysyłka leków za granicę", 
                 "dostawa LSD",
                 "cena LSD"]

#mapping = {0:"dostawa", 1:"bulk", 2:"designer", 3:"narkotyki", 4:"nienarkotyki", 5:"harddrugs", 6:"medicijnen", 7: "pickup", 8: "post", 9:"softdrugs"}
predictions = pipeline.predict(text_messages)
predicted_labels = mlb.inverse_transform(predictions)

print("Predictions for Sample Texts:")
for text, labels in zip(text_messages, predicted_labels):
    print(f"{text}: {labels}")


Predictions for Sample Texts:
wysyłka leków za granicę: ('dostawa', 'nienarkotyki')
dostawa LSD: ('dostawa', 'narkotyki')
cena LSD: ('cena', 'narkotyki')


In [13]:
# Evaluate the model using Hamming Loss and accuracy per label
from sklearn.metrics import hamming_loss
hloss = hamming_loss(y_test, y_train)
accuracy = 1 - hloss

ValueError: Found input variables with inconsistent numbers of samples: [20, 77]

In [ ]:
#labels = []

#for message in clf.predict(text_messages): 
    #label = []
    #for idx, labeled in enumerate(message):
        #if labeled == 1:
            #label.append(mapping[idx])
    #labels.append(label)
    
#print(labels)

